version: "2.2"
services:
  node1:
    image: redis
    container_name: node1
    ports:
      - 6379:6379
    volumes:
      - ./node1/redis.conf:/etc/redis/redis.conf:rw
      - ./node1/data/:/data/:rw

